services:
  mysqldb:
    image: mysql:5.7
    container_name: a3-mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    expose:
      - ${MYSQL_DOCKER_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: a3-api
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_LOCAL_PORT}"

  sales-reports:
    build:
      context: ./relatorios
      dockerfile: Dockerfile
    container_name: a3-sales-reports
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${SALES_REPORTS_PORT}:${SALES_REPORTS_PORT}"
